previousnext/agov

.pnxci.yml
What this does:
* Adds a .pnxci.yml file to total control of the environment build process.
* PR and HEAD environments (http://demo.agov.com.au)
=> Adds .pnxci.yml

modules/custom/agov_dynamic_content/modules/agov_paragraphs/src/ClassController.php, modules/custom/agov_dynamic_content/modules/agov_styles/agov_styles.install
=> [#28576] Update hook for change from style to paragraph_style

themes/agov/agov_zen/css/agov_styles.css, themes/agov/agov_zen/sass/components/_search.scss, themes/agov/agov_zen/sass/sections/_header.scss, themes/agov/agov_zen/template.php
Steps to test:
Check funnelback search block in the header looks as follows:
=> 26291 theme funnelback search

drupal-org.make
Accidentally removed in last security update
=> Re-apply entity api patch

.travis.yml, build.xml, composer.json, composer.lock
Steps to test:
- composer install
- phing
=> Use composer to install drush

themes/agov/agov_whitlam/kss-config.json
=>  Modify path of the css files in kss-config.json file

themes/agov/agov_whitlam/sass/_variables.scss, themes/agov/agov_whitlam/sass/base/links/_links.scss
=> Add link styling

themes/agov/agov_whitlam/sass/_variables.scss, themes/agov/agov_whitlam/sass/base/links/_links.scss
Update link style, please review it.
=> 31029 link styling

themes/agov/agov_barton/css/styles.css, themes/agov/agov_barton/sass/styles.scss, themes/agov/agov_zen/css/agov_styles.css, themes/agov/agov_zen/sass/_colors.scss, themes/agov/agov_zen/sass/_mixins.scss, themes/agov/agov_zen/sass/components/_text-resize.scss, themes/agov/agov_zen/sass/sections/_footer.scss, themes/agov/agov_zen/sass/sections/_header.scss, themes/agov/agov_zen/sass/sections/_navigation.scss, themes/agov/agov_zen/sass/sections/_slideshow.scss
There should be no more contrast errors
=> 31865 colour contrast

themes/agov/agov_zen/css/agov_styles.css, themes/agov/agov_zen/sass/_mixins.scss
Fix navbar h2's colour contrast when logged in
=> [#31865] force invisible elements to inherit parent colour

agov.install
@kimpepper , please review and merge.
=> [#31957] add header default blocks

modules/features/agov_promotion/agov_promotion.features.inc, modules/features/agov_promotion/agov_promotion.info, modules/features/agov_promotion/agov_promotion.views_default.inc
https://redmine.previousnext.com.au/issues/31999
=> [#31999] update block promotion in home page

themes/agov/agov_whitlam/sass/components/button/_button.scss
Add large button variant
https://agov_pr526.agov.com.au/styleguide/agov_whitlam/section-components.html#kssref-components-button
=> [#31080] Add large button

themes/agov/agov_whitlam/template.php, themes/agov/agov_whitlam/templates/page.tpl.php
Implement the logic to generate content and sidebars classes in template file.
=> [#32091] Generate content sidebars classes

themes/agov/agov_zen/templates/page.tpl.php
Made the logo alt more accessible. Should be the same as the site name
=> [#33088] Added an accessible alt tag for logo

themes/agov/agov_whitlam/sass/components/navbar/_navbar.scss
Steps to test:
Navigate to main nav via the keyboard.
Before:
After:
=> [#32296] Fixed submenu items on keyboard nav

themes/agov/agov_whitlam/sass/components/header/_header.scss, themes/agov/agov_whitlam/sass/components/search/_search.scss, themes/agov/agov_whitlam/template.php
Steps to test:
Check search form on the /search page is themed as follows:
@TODO - update styleguide once reviewed by John.
=> 32413 Fix search form search results

themes/agov/agov_whitlam/sass/components/button/_button.scss
Steps to test:
Go to /contact
Check that submit button is bold
Before:
After:
=> [#32867] Made buttons bold

themes/agov/agov_whitlam/sass/components/header/_header.scss, themes/agov/agov_whitlam/sass/components/navbar/_navbar.scss
Steps to test:
Check on 'mobile' view logo and hamburger icon look as follows:
=> 32869 scale logo mobile

themes/agov/agov_whitlam/sass/components/footer-top/_footer-top.scss
Check secondary footer menu looks as follows:
[](https://dl.dropbox.com/s/whwb0fqacb25kho/Screenshot%202015-07-23%2017.58.16.png?dl=0)
=> [#32429] Themed nested footer menu

modules/features/agov_news/agov_news.pages_default.inc, themes/agov/agov_whitlam/sass/components/divider/_divider.scss, themes/agov/agov_whitlam/template.php
Steps/What to test:
Check that all landing page Quick links look as follows:
Before:
After:
=> 32284 theme quicklinks

modules/features/agov_basic_page/agov_basic_page.features.field_instance.inc
Steps to test:
- Go to standard content type: /admin/structure/types/manage/page/display/teaser
- Check teaser that file is hidden ![](https://dl.dropbox.com/s/dlcjijso6z9ij1v/Screenshot%202015-08-12%2010.26.20.png?dl=0)
=> [#34032] Removed file from teaser view mode

modules/features/agov_front/agov_front.views_default.inc, themes/agov/agov_whitlam/node--event--compact.tpl.php, themes/agov/agov_whitlam/templates/node--news-article--compact.tpl.php
What to test:
Check that 'latest updates' on the front page is sorted by the date field rather than the post date.
=> 34089 sort by date

.pnxci.yml, build.xml
Do not commit, this depends on https://github.com/previousnext/pnx-ci/pull/25
=> [#32425] Add d.o sync job with assets for 7.x-3.x.

.pnxci.yml
So before we make any changes to local and commit, we need to merge the previous d.o commits back first.
=> [#32425] Cannot push -f to d.o

agov/agov.info.yml, agov/drupal-org.make, agov/modules/custom/agov_default_content/agov_default_content.info.yml, agov/modules/custom/agov_default_content/config/optional/block.block.stayuptodate.yml, agov/modules/custom/agov_default_content/content/block_content/social-block.json, agov/modules/custom/agov_social_icons/agov_social_icons.info.yml, agov/modules/custom/agov_social_icons/config/install/block_content.type.social_block.yml, agov/modules/custom/agov_social_icons/config/install/core.entity_form_display.block_content.social_block.default.yml, agov/modules/custom/agov_social_icons/config/install/core.entity_view_display.block_content.social_block.default.yml, agov/modules/custom/agov_social_icons/config/install/field.field.block_content.social_block.field_social_icon.yml, agov/modules/custom/agov_social_icons/config/install/field.storage.block_content.field_social_icon.yml, agov/themes/agov/agov_whitlam/sass/components/social/_social.scss
Note, i set the icons to only appear on <front> but we don't have a homepage configured yet so you have to go and set homepage to /node/1 to see the icons.
=> Social icons, default content block placement on homepage.

.pnxci.yml
What this does:
* Abstracts the d.o pushing from Jenkins, into the project.
Where from here:
* Add a "target" in pnx-ci for "deploy_8x_1x"
=> Adds d.o push to 8.x branch

agov/modules/custom/agov_default_content/content/block_content/social-block.json
Depends on https://redmine.previousnext.com.au/issues/35779 being resolved.
=> [WIP] 35779 social media icons should have longer link text

agov/modules/custom/agov_default_content/content/block_content/social-block.json
=> Revert "[WIP] 35779 social media icons should have longer link text"

agov/drupal-org-core.make, agov/themes/agov/agov_base/agov_base.info.yml
Info here: https://www.drupal.org/node/2613744
=> [#2613744] Allow people to upload logos.

composer.lock
This fixes errors in the console during installation.
=> Bump the version of drush.

agov/themes/agov/agov_base/agov_base.libraries.yml, agov/themes/agov/agov_base/sass/_init.scss, agov/themes/agov/agov_base/sass/base/fonts.scss, agov/themes/agov/agov_base/sass/styles.scss
=> [#2700191] fix font-awesome path
